# Generated by Django 5.0.2 on 2024-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('residence_type', models.CharField(max_length=50)),
                ('tenure_type', models.CharField(max_length=50)),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('furnishing', models.CharField(max_length=50)),
                ('extra_facilities', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location_category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='PropertyImage/')),
                ('image2', models.ImageField(upload_to='PropertyImage/')),
                ('image3', models.ImageField(upload_to='PropertyImage/')),
            ],
        ),
    ]
