# Generated by Django 5.0.2 on 2024-03-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='image',
            field=models.ImageField(default=0, upload_to='PropertyImage/'),
            preserve_default=False,
        ),
    ]
